Transform: AWS::Serverless-2016-10-31
Description: >
  Sagemaker Notebook VendingMachine Template
Parameters:
  Environment:
    Type: String   
Resources:
###
# API
### 
  apiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  smnbstackcreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Role: !GetAtt smnbstackcreateLambdaRole.Arn
      Handler: app.handler
      Timeout: 120
      PackageType: Image  
      ImageUri: ${AWS::Account}.dkr.ecr.${AWS::Region}.amazonaws.com/smnbstackcreate:latest  
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /smnbstackcreate
            Method: POST
            RestApiId:
              Ref: apiGateway

  smnbstackinfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Role: !GetAtt smnbstackinfoLambdaRole.Arn
      Handler: app.handler
      Timeout: 120
      PackageType: Image
      ImageUri: ${AWS::Account}.dkr.ecr.${AWS::Region}.amazonaws.com/smnbstackinfo:latest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /smnbstackinfo
            Method: POST
            RestApiId:
              Ref: apiGateway

  smnbstackcleanupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Role: !GetAtt smnbstackcleanupLambdaRole.Arn
      Handler: handler.function
      Timeout: 120
      PackageType: Image
      Code:
        ImageUri: ${AWS::Account}.dkr.ecr.${AWS::Region}.amazonaws.com/smnbstackcleanup:latest
      Environment:
        Variables:
          PROVISIONED_PRODUCT_MAX_TTL_SEC: 86400
      Events:
        CheckProductScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)

###
# Roles 
###
  smnbstackcreateLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: logs_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "*"
        - PolicyName: cf_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - "cloudformation:Describe*"
              Resource: "*"
      Path: "/"

  smnbstackinfoLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: logs_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "*"
        - PolicyName: cf_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - "cloudformation:Describe*"
              Resource: "*"
      Path: "/"

  smnbstackcleanupLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: logs_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "*"
        - PolicyName: cf_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
                - "cloudformation:Describe*"
              Resource: "*"
      Path: "/"

Outputs:

  
  smnbstackcreateInvokeURL:
    Value: !Sub https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/${apiGatewayVersionResource}/${apiGatewaysmnbstackcreateResource}
  smnbstackinfoInvokeURL:
    Value: !Sub https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/${apiGatewayVersionResource}/${apiGatewaysmnbstackinfoResource}
  smnbstackcreateFunctionArn:
    Value: !Sub smnbstackcreateFunction.Arn
  smnbstackinfoFunctionArn:
    Value: !Sub smnbstackinfoFunction.Arn
  smnbstackcleanupFunctionArn:
    Value: !Sub smnbstackcleanupFunction.Arn
  

  
